export const contextFields = [
  { id: "checkedBy", type: "text", required: "false" },
  { id: "enteredBy", type: "text", required: "false" },
  { id: "eastings", type: "number", required: "false" },
  { id: "northings", type: "number", required: "false" },
  { id: "excavator", type: "text", required: "false" },
  { id: "excavatedOn", type: "text", required: "false" },
  { id: "recorder", type: "text", required: "false" },
  { id: "composition", type: "text", required: "false" },
  { id: "description", type: "text", required: "false" },
  { id: "notes", type: "text", required: "false" },
  { id: "contextType", type: "text", required: "false" },
  { id: "setNum", type: "number", required: "false" },
  { id: "thickness", type: "number", required: "false" },
  { id: "fillOf", type: "number", required: "false" },
  { id: "associatedWith", type: "text", required: "false" },
  { id: "siteArea", type: "text", required: "false" },
  { id: "excavationMethod", type: "text", required: "false" },
  { id: "earliestDate", type: "datetime-local", required: "false" },
  { id: "latestDate", type: "datetime-local", required: "false" },
  { id: "spotX", type: "number", required: "false" },
  { id: "spotY", type: "number", required: "false" },
  { id: "dateText", type: "text", required: "false" },
  { id: "excavationEnd", type: "datetime-local", required: "false" },
  { id: "period", type: "text", required: "false" },
  { id: "dimensions", type: "text", required: "false" },
];

/* 
  sieved: { type: Boolean, required: false },
  completed: { type: Boolean, required: false },
  planNA: { type: Boolean, required: false },
  */
